### ISSUE TITLE
Theme Gruvbox for launcher

### ISSUE THREAD

**Issue by ghost** [FreesmTeam/FreesmLauncher#1]
# Description
Good afternoon, I created a gruvbox theme for prismlauncher, and as I understand it can work in other forks besides multimc. Is it possible to add it to freesmlauncher?
## Also....
I was asked to do it by hand7s, well, and a screenshot that it's real.
![20240715_16h31m22s_grim](https://github.com/user-attachments/assets/d690b8ff-c5c2-4700-9f27-175dfd60a0cd)

**Comment by s0me1newithhand7s** [comment]
LGTM, i'm for
