### ISSUE TITLE
Mods categorization.

### ISSUE THREAD

**Issue by DeL1TMe** [FreesmTeam/FreesmLauncher#4]
### Role

Собираю модпаки.

### Suggestion

Я хочу чтобы можно было покрасить в определённый цвет выбранные моды и назначить им категорию: например оптимизация.

### Benefit

Гораздо проще будет работать с модпаками и их созданием, обновлением, настройкой.

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by s0me1newithhand7s** [comment]
that's a solid thing but sadly - as a fork of Prism - implementing this might and will take time needed to fix "upstream not build" issue

i suggest open similar issue on a github.com/PrismLauncher/PrismLauncher, but on English pls :D

**Comment by kaeeraa** [comment]
@DeL1TMe actually we can implement it now

**Comment by kaeeraa** [comment]
reopen if still needed

**Comment by notwindstone** [comment]
> @DeL1TMe actually we can implement it now

seems like prismlauncher team already did that in https://github.com/PrismLauncher/PrismLauncher/pull/3249

**Comment by s0me1newithhand7s** [comment]
> > @DeL1TMe actually we can implement it now
> 
> seems like prismlauncher team already did that in [PrismLauncher/PrismLauncher#3249](https://github.com/PrismLauncher/PrismLauncher/pull/3249)

# NICE

**Comment by notwindstone** [comment]
![изображение](https://github.com/user-attachments/assets/d5c14bf2-d2c5-4b96-a869-ccefa2f32fa4)

**Comment by kaeeraa** [comment]
> ![изображение](https://private-user-images.githubusercontent.com/91563727/402954623-d5c14bf2-d2c5-4b96-a869-ccefa2f32fa4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY4ODQ4NDcsIm5iZiI6MTczNjg4NDU0NywicGF0aCI6Ii85MTU2MzcyNy80MDI5NTQ2MjMtZDVjMTRiZjItZDJjNS00Yjk2LWE4NjktY2NlZmEyZjMyZmE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTE0VDE5NTU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmYjQxZDY1Y2E2YzMzMjdhMDJkMDBiZDk2M2Q5YTljNjdjMWQ2ZjIyZDE1Y2NiOTc1MjAzZjAyYjZkMTk0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QqLBXBCmZr19hubaryaaT0yGsir02-2uLml34LqojV4)

someone should open new issue here

**Comment by kaeeraa** [comment]
i want to implement this
